### ISSUE TITLE
API discards user's time zone

### ISSUE THREAD

**Issue by giorgia** [tomatoes-app/tomatoes#264]
Just fix it!

**Comment by bugant** [comment]
Can you please be more precise? Also maybe reproduction steps or an example of API call and its wrong returned response would help.

**Comment by potomak** [comment]
@bugant my fault: I was the one reporting this issue yesterday from @giorgia's account.

The issue is that API requests don't take user's time zone in consideration.

If a user in `America/New_York` creates a tomato at 18:59, that is 23:59 UTC in this period of the year, counters will be off by one between 19:00 and 23:59 `America/New_York`, because it's a new day in the UTC time zone, that is the default time zone used by the app.

I think to prevent this issue we should use a similar approach we're using for non-API requests. We set request's time zone using the client's time zone or user's time zone as a fallback. See https://github.com/tomatoes-app/tomatoes/blob/0.13.1/app/controllers/application_controller.rb#L26-L32.

My proposal is to get the time zone name from a request parameter or a header value, like we do for the auth token, and fallback to user's time zone if a time zone name is not present.

I'd say the API could accept a `time_zone` request parameter or a `Time-Zone` header with a time zone name, e.g. `America/New_York`.

**Comment by bugant** [comment]
OK @potomak it make sense. I like the header much than parameter but OK to have both.

Also I don't want to be unpolite with @giorgia, sorry if it did sound like that... I was just asking for more info to be able to work on the issue :-)
