### ISSUE TITLE
Add spanish translation config

### ISSUE THREAD

**Issue by cristianzamar** [tomatoes-app/tomatoes#289]
I tried to translate the headings "Today's tomatoes" and "Today's projects" but I couldn't find the configs inside es.yml. Could you please add them??
The translations are: "Tomates de Hoy" and "Proyectos de Hoy", respectively.

**Comment by potomak** [comment]
@cristianzamar good catch!
They're respectively in https://github.com/tomatoes-app/tomatoes/blob/master/app/views/welcome/_tomatoes_list.html.erb and https://github.com/tomatoes-app/tomatoes/blob/master/app/views/welcome/_projects_list.html.erb.

If you want to add those translations in the view templates, go for it. It should be a self contained PR. Otherwise I'll do it, hopefully before the end of the week.

Thanks!

**Comment by potomak** [comment]
@cristianzamar I just released a new version (0.14.4) with these two missing translations!

Thanks for reporting it.
