### ISSUE TITLE
Alternative to BackerPass

### ISSUE THREAD

**Issue by potomak** [tomatoes-app/tomatoes#310]
BackerPass, the service that we're currently using to accept donations for paying for Tomatoes hosting services, is sunsetting. We have until the end of January to find a replacement and to migrate current users donations.

What would be a good alternative to accept donations for the project?
What strategy we can use to migrate current donations?
How can we communicate to current donors about this migration?

Current (public) donors list:
* @trystant
* @jakesnell
* @manzwebdesigns
* @johnkrane
* @potomak
* @andrew-chiz-muzychuk
* @twirm
* @K5b489pIg65C
* @eclecticlibrarian
* @babaliba
* @Cobradabest

cc @bugant @dalpo @gragland

**Comment by gragland** [comment]
I would recommend https://opencollective.com or https://patreon.com. Open Collective seems to be the most common for open source projects, as it has some features that OSS tends to want (like visibility into finances, ability for multiple contributors to get paid out, etc). But I think Patreon would also work reasonably well. Hopefully you can get some feedback from current donors (or other people that have yet to donate) since if most have an account with one of those platforms that might be the one to go with.

**Comment by babaliba** [comment]
I would recommend whatever reduces processing and payment costs.

As a donor I would appreciate the choice to pay for longer periods. For me a yearly payment would work better. Also the option to get at least a receipt (I do not need a proper invoice) would be great.

Thanks for the service anyway! I temporally tried another pomodoro methods due to a project without proper internet connection and I missed my daily and weekly rankings.

**Comment by babaliba** [comment]
Credit card expense line is fine. I just mention it because supporting other projects I get a more detailed expense report. Having said that do not worry about it.

A bare Stripe account could work. 10% for OpenCollective seems a lot of money I would prefer that money going to the project directly

**Comment by manzwebdesigns** [comment]
Maybe I am a bit naive, but couldn't we each one just setup a recurring charge on our bank to pay you directly?

**Comment by babaliba** [comment]
Recurring banking charges could be an issue for other currencies. For those like @manzwebdesigns it could work and that should be fine. Could Paypal be an alternative for those like me with bank accounts in Euros?

**Comment by andrew-chiz-muzychuk** [comment]
Or for those Stone Age countries like Belarus.

**Comment by potomak** [comment]
Existing Stripe accounts have been migrated, thanks @gragland, but I think the easier choice is OpenCollective. I will setup the account soon.

Thanks for your feedback.
